
const webpack = require('webpack');
const merge = require('webpack-merge');
const common = require('./webpack.common.config');
const path = require('path');

const Extract = require('extract-text-webpack-plugin');
const Clean = require('clean-webpack-plugin');
const Uglify = require('uglifyjs-webpack-plugin');

const config = merge(common,{
	output : {
		path : path.resolve(__dirname, 'build'),
		filename : "[name].[chunkhash:5].js",
		chunkFilename : '[name].[chunkhash:5].chunk.js'
	},

	devtool : 'source-map',

	module : {
		rules : [
			//STYLE PROCESS
			{
				test : /\.s?css$/,
				use: Extract.extract({
					fallback :  'style-loader',
					use : [
						{ loader: 'css-loader', options: { importLoaders: 1 } },
						'postcss-loader',
						"sass-loader"
					]
				})
			},
		]
	},

	plugins : [
		/** SET THIS ENVIRONMENT AS A TYPE OF `PRODUCTION` SO THIRD PARTY LIBRARIES ACT ACCORDINGLY */
		new webpack.DefinePlugin({
			'process.env.NODE_ENV': JSON.stringify('production')
		}),
		/**  THIS PLUGIN JOIN PLUGINS THAT ARE USED IN MORE THAN ONE MODULE */
		new webpack.optimize.CommonsChunkPlugin({
			names : ['vendor','manifest'],
			minChunks: Infinity
		}),
		/**  EXTRACT THE FINAL STYLESHEET */
		new Extract("app.[hash:5].css"),
		/**  UGLIFY THE FINAL JS CODE */
		new Uglify({ sourceMap : true }),
		/** CLEAN THE OLD CONTENT GENERATED BY A 'NPM RUN BUILD' COMMAND */
		new Clean(["build"]),
		
		new webpack.NamedModulesPlugin()
  ]
});

module.exports = config;